spring.application.name=Hogwarts
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:liquibase/lesson-three.yml
spring.liquibase.enabled=true

logging.level.school.Hogwarts.service=INFO
logging.level.com.example.service.FacultyService=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

server.port = 8080

